### ISSUE TITLE
PHP 5.5.24 / Wheezy : tsrm_virtual_cwd.c: No such file or directory

### ISSUE THREAD

**Issue by Seraf** [gplessis/dotdeb-php5#82]
Hello,

A customer trying to import a price table on a Magento backoffice hit a 502 error. I checked in the logs and found that PHP had a segfault.

Here is my version : 
PHP 5.5.24-1~dotdeb+wheezy.1 (cli) (built: Apr 22 2015 05:54:24) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

Here is the segfault : 
```
root@BACKOFFICE-EU-PREPROD:/usr/src/php5.5/source/dotdeb-php5# gdb /usr/sbin/php5-fpm /tmp/coredump-php5-fpm.31145 
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/php5-fpm...Reading symbols from /usr/lib/debug/usr/sbin/php5-fpm...done.
done.
[New LWP 31145]

warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php-fpm: pool www                                                     '.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000669b80 in tsrm_realpath_r (path=path@entry=0x7ffffc60e090 "/magmi.ini", start=start@entry=1, 
    len=len@entry=10, ll=ll@entry=0x7ffffc60e084, t=t@entry=0x7ffffc60e088, use_realpath=use_realpath@entry=1, 
    is_dir=is_dir@entry=0, link_is_dir=link_is_dir@entry=0x0)
    at /usr/src/php5.5/source/dotdeb-php5/TSRM/tsrm_virtual_cwd.c:751

warning: Source file is more recent than executable.
751	{
```

```
(gdb) bt
#0  0x0000000000669b80 in tsrm_realpath_r (path=path@entry=0x7ffffc60e090 "/magmi.ini", start=start@entry=1, 
    len=len@entry=10, ll=ll@entry=0x7ffffc60e084, t=t@entry=0x7ffffc60e088, use_realpath=use_realpath@entry=1, 
    is_dir=is_dir@entry=0, link_is_dir=link_is_dir@entry=0x0)
    at /usr/src/php5.5/source/dotdeb-php5/TSRM/tsrm_virtual_cwd.c:751
#1  0x000000000066abc5 in virtual_file_ex (state=state@entry=0x7ffffc60f0e0, 
    path=path@entry=0x37b9878 "/magmi.ini", verify_path=verify_path@entry=0, use_realpath=use_realpath@entry=1)
    at /usr/src/php5.5/source/dotdeb-php5/TSRM/tsrm_virtual_cwd.c:1292
#2  0x0000000000673f05 in expand_filepath_with_mode (filepath=filepath@entry=0x37b9878 "/magmi.ini", 
    real_path=real_path@entry=0x0, relative_to=relative_to@entry=0x0, relative_to_len=relative_to_len@entry=0, 
    realpath_mode=realpath_mode@entry=1) at /usr/src/php5.5/source/dotdeb-php5/main/fopen_wrappers.c:797
#3  0x000000000067407b in expand_filepath_ex (filepath=filepath@entry=0x37b9878 "/magmi.ini", 
    real_path=real_path@entry=0x0, relative_to=relative_to@entry=0x0, relative_to_len=relative_to_len@entry=0)
    at /usr/src/php5.5/source/dotdeb-php5/main/fopen_wrappers.c:740
#4  0x0000000000674089 in expand_filepath (filepath=filepath@entry=0x37b9878 "/magmi.ini", 
    real_path=real_path@entry=0x0) at /usr/src/php5.5/source/dotdeb-php5/main/fopen_wrappers.c:732
#5  0x000000000068ca7a in _php_stream_fopen (filename=0x37b9878 "/magmi.ini", mode=0x7f0553eed858 "w", 
    opened_path=0x0, options=0) at /usr/src/php5.5/source/dotdeb-php5/main/streams/plain_wrapper.c:943
#6  0x0000000000688132 in _php_stream_open_wrapper_ex (path=0x37b9878 "/magmi.ini", mode=0x7f0553eed858 "w", 
    options=8, opened_path=opened_path@entry=0x0, context=0x7f0553435b48)
    at /usr/src/php5.5/source/dotdeb-php5/main/streams/streams.c:2064
#7  0x00000000005ff58d in php_if_fopen (ht=<optimized out>, return_value=0x42e62b8, 
    return_value_ptr=<optimized out>, this_ptr=<optimized out>, return_value_used=<optimized out>)
    at /usr/src/php5.5/source/dotdeb-php5/ext/standard/file.c:877
#8  0x0000000000538b03 in phar_fopen (ht=2, return_value=0x42e62b8, return_value_ptr=0x0, this_ptr=0x0, 
    return_value_used=1) at /usr/src/php5.5/source/dotdeb-php5/ext/phar/func_interceptors.c:418
#9  0x00000000006c0049 in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, 
    return_value_used=<optimized out>) at /usr/src/php5.5/source/dotdeb-php5/Zend/zend_dtrace.c:97
#10 0x0000000000780ccb in zend_do_fcall_common_helper_SPEC (execute_data=0x42f70d8)
    at /usr/src/php5.5/source/dotdeb-php5/Zend/zend_vm_execute.h:552
```

```
(gdb) frame 0
#0  0x0000000000669b80 in tsrm_realpath_r (path=path@entry=0x7ffffc60e090 "/magmi.ini", start=start@entry=1, len=len@entry=10, ll=ll@entry=0x7ffffc60e084, t=t@entry=0x7ffffc60e088, use_realpath=use_realpath@entry=1, is_dir=is_dir@entry=0, 
    link_is_dir=link_is_dir@entry=0x0) at /usr/src/php5.5/source/dotdeb-php5/TSRM/tsrm_virtual_cwd.c:751
751	{
(gdb) print (char *)executor_globals.active_op_array->function_name
$1 = 0x7f05557565c0 "write_ini_file"
(gdb) print (char *)executor_globals.active_op_array->filename
$2 = 0x7f0555751708 "/home/client/magento/magmi/inc/properties.php"
```
Even if PHP code may be faulty, I think it isn't a normal behavior to segfault. I don't know if it's related to a PHP bug or a packaging problem, but I wanted to have your advice first.

Thanks

**Comment by Seraf** [comment]
Totally sorry, after some debug and play with gdb, I found the magmi.ini wasn't present on the server and the code try to write in the file even if it's not opened ...

So not related to dotdeb, I close this issue, sorry for the noise
